sonar.projectKey=simiancraft_Gmail-MCP-Server
sonar.organization=simiancraft

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=**/*.test.ts,dist/**,node_modules/**

sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
